### ISSUE TITLE
Edit the Player Class

### ISSUE THREAD

**Issue by JoanWithTehBone** [JoanWithTehBone/Trip#11]
Add stats to the player and create a new character that walks around!
Create Interaction with Colliding Objects on button press!

**Comment by JaneVick01** [comment]
I have added a new class house in my branch, created a new object in level, for now it has a random location everytime you start it. You can interact with it and for now it just says 'Interact' in the console.

**Comment by JoanWithTehBone** [comment]
Thats really nice, thank you! I'm gonna merge it so everyone gets to try it out!
